version: '3.8'
services:
  movies:
    image: madhusudhannandyala/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 2
  train:
    image: madhusudhannandyala/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 2
  dth:
    image: madhusudhannandyala/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: madhusudhannandyala/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 2
